# Generated by Django 5.0.6 on 2024-05-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
