# Generated by Django 5.0.6 on 2024-05-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Phone',
        ),
    ]
